language: node_js

os: linux
dist: xenial

node_js:
    - 16
    - lts/*

notifications:
    email:
        on_success: never

script:
    - yarn
    - yarn dev:prepare
    - yarn lint
    - yarn test
