export type Type =
    | 'checkbox'
    | 'checkbox-group'
    | 'date'
    | 'email'
    | 'file'
    | 'number'
    | 'password'
    | 'radio-group'
    | 'row'
    | 'select'
    | 'static-text'
    | 'submit'
    | 'tel'
    | 'text'
    | 'textarea'
    | 'url'
