name: Publish Development

on:
  push:
    branches:
      - "develop"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: remindgmbh/npm-publish-dev-action@v1.0.0
        with:
          node-version: 20
          npm-token: ${{ secrets.NPM_TOKEN }}
