name: Publish Development

on:
  push:
    branches:
      - "develop"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: remindgmbh/semantic-release-action@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 20
          npm-token: ${{ secrets.NPM_TOKEN }}
          type: npm-pre
